services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: app_php
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        depends_on:
            - postgres
            - redis
            - rabbitmq
        environment:
            APP_ENV: dev

    nginx:
        image: nginx:stable-alpine
        container_name: app_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    postgres:
        image: postgres:16
        container_name: app_postgres
        environment:
            POSTGRES_DB: symfony
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        container_name: app_redis
        ports:
            - "6379:6379"

    rabbitmq:
        image: rabbitmq:3-management
        container_name: app_rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    smtp:
        image: namshi/smtp
        container_name: smtp
        ports:
            - "1025:25"

volumes:
    pgdata:
